version: "3.8"
services:
  discordNfStatsBot:
    build: ./
    image: discord-nft-stats-bot:latest
    container_name: discord-nft-stats-bot-prod
    restart: always
    stdin_open: true
    tty: true
    environment:
      SPRING_APPLICATION_JSON: |-
        {"nft-bot": {
            "apiKeyOpensea": "d2feaeeba3064812a1ba8ec2fe6046e3",
            "discord": {
              "token": "",
              "commandPrefix": "%"
            },
            "stats[0]": {
              "contractAddress": "",
              "interval": "",
              "enableHolders": true,
              "holdersOutputChannelId": "922252219716341830"
            }
        }
    healthcheck:
      test: ["CMD-SHELL", "bash -c \"if [[ $$(tail -n 10 /tmp/nftBotRuntime.log | grep -cE '(Websocket)') -gt 5 ]]; then echo 1; else echo 0; fi\""]
      interval: 60s
      timeout: 30s
      retries: 2